name: Publish to PyPI

on:
    release:
        types: [published]

jobs:
    build-and-publish:
        name: Build and publish Python distributions to PyPI
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        environment:
            name: pypi-release

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
                  
            - name: install uv
              run: python -m pip install uv
            
            - name: Build package
              run: uv build

            - name: Publish package
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  package-dir: dist/